version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x86
    Qt: 5.13.0
    releaseName: Underground_qt512_vs2017_x86
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64
    Qt: 5.13.0
    releaseName: Underground_qt512_vs2017_x64
build_script:
- cmd: >-
    if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set msvc=msvc2017

    if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set vs=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build

    if "%platform%"=="x86" set QTDIR=C:\Qt\%qt%\%msvc%

    if "%platform%"=="x64" set QTDIR=C:\Qt\%qt%\%msvc%_64

    set PATH=%PATH%;%QTDIR%\bin;

    if "%platform%"=="x86" set vcvarsall=%vs%\vcvarsall.bat

    if "%platform%"=="x64" set vcvarsall=%vs%\vcvarsall.bat

    if "%platform%"=="x86" call "%vcvarsall%" x86

    if "%platform%"=="x64" call "%vcvarsall%" x64

    qmake C:\projects\underground\maze_mvvm\maze_mvvm.pro

    nmake
after_build:
- cmd: >-
    if "%APPVEYOR_REPO_TAG%"=="true" windeployqt release\maze_mvvm.exe --qmldir %QTDIR%\qml
artifacts:
    path: release
    name: $(releaseName)
deploy:
    provider: GitHub
    auth_token: $(GITHUB_OAUTH_TOKEN)
